### ISSUE TITLE
Audio doesn't work on build

### ISSUE THREAD

**Issue by jerdog** [sonyxperiadev/device-sony-yuga#3]
Audio doesn't work on the AOSP build

```
W/AudioTrack(  567): obtainBuffer timed out (is the CPU pegged?) 0x71ce8ca0 name=0x13user=00000eb3, server=00000000
W/AudioTrack(  567): obtainBuffer timed out (is the CPU pegged?) 0x71957710 name=0x12user=00000eb3, server=00000000
E/alsa_pcm(  176): cannot open device '/dev/snd/pcmC0D14p', errno 12
D/ALSAModule(  176): setHardwareParams: reqBuffSize 1024 channels 2 sampleRate 48000
E/alsa_pcm(  176): SNDRV_PCM_IOCTL_HW_REFINE failed
E/ALSAModule(  176): cannot set hw params
E/ALSAModule(  176): Set HW/SW params failed: Closing the pcm stream
D/alsa_ucm(  176): snd_use_case_set(): uc_mgr 0x416e6210 identifier _verb value Inactive
D/alsa_ucm(  176): Set mixer controls for HiFi Lowlatency enable 0
D/alsa_ucm(  176): snd_use_case_set(): uc_mgr 0x416e6210 identifier _disdev value Speaker
D/alsa_ucm(  176): Set mixer controls for Speaker enable 0
E/AudioStreamOutALSA(  176): write:: device open failed
D/AudioStreamOutALSA(  176): mHandle->useCase: HiFi Lowlatency
D/ALSAModule(  176): s_route: devices 0x2 in mode 0
D/ALSAModule(  176): switchDevice: device 2 mode:0
D/ALSAModule(  176): s_is_tmus: mnc_mcc :  0
D/ALSAModule(  176): s_is_tmus: mnc_mcc :  0
D/ALSAModule(  176): No valid input device: 0
D/ALSAModule(  176): switchDevice,rxDev:Speaker, txDev:(null), curRxDev:Speaker, curTxDev:None
D/alsa_ucm(  176): snd_use_case_set(): uc_mgr 0x416e6210 identifier _enadev value Speaker
D/ALSAModule(  176): switchDevice: curTxUCMDevivce None curRxDevDevice Speaker
D/alsa_ucm(  176): snd_use_case_set(): uc_mgr 0x416e6210 identifier _verb value HiFi Lowlatency
D/alsa_ucm(  176): Set mixer controls for Speaker enable 1
D/ACDB-LOADER(  176): ACDB -> send_audio_cal, acdb_id = 14, path =  0
D/ACDB-LOADER(  176): ACDB -> send_adm_topology
D/ACDB-LOADER(  176): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
D/ACDB-LOADER(  176): ACDB -> send_audtable
D/ACDB-LOADER(  176): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
D/ACDB-LOADER(  176): ACDB -> AUDIO_SET_AUDPROC_CAL
D/ACDB-LOADER(  176): ACDB -> send_audvoltable
D/ACDB-LOADER(  176): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_VOLTBL_STEP_COPP
D/ACDB-LOADER(  176): ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
D/ACDB-LOADER(  176): ACDB -> AUDIO_SET_AFE_CAL
W/AudioFlinger(  176): write blocked for 20160 msecs, 10 delayed writes, thread 0x41736a88
D/alsa_ucm(  176): Set mixer controls for HiFi Lowlatency enable 1
D/ALSAModule(  176): Device value returned is hw:0,14
```

**Comment by Kali-** [comment]
this should fix audio
http://review.cyanogenmod.org/#/c/36967/

**Comment by jredestig** [comment]
Did you actually try this and it works for you? With no other changes?

**Comment by Kali-** [comment]
on CM10.1, yes
guess the problem exists on aosp too

**Comment by jredestig** [comment]
Ok. I assume that CM10.1 has updates to qcom/audio that makes that change useful. Reducing the period size actually breaks audio for me due since the hal requests the higher.

**Comment by adrian-bl** [comment]
This is enough to get audio working on AOSP (using the 253 kernel)
https://github.com/adrian-bl-yuga/android_hardware_qcom_audio/commit/b8d1e0e197ebee314daeb969f185c2401eb7700f

**Comment by Kali-** [comment]
why use 253 kernel when there is a 4.2.2 kernel?

**Comment by adrian-bl** [comment]
Because i am using the camera blobs from the 253 release:
The ioctl request numbers used by the 253-camera blobs do not match with the IDs used in the 'aosp sony' kernel and i do not see any benefit in patching up the slightly newer kernel given the fact that the 253 release works just fine. (And the aosp-kernel also needs some 'beating' to get sound 100% working on AOSP)

**Comment by Kali-** [comment]
i guess not only camera but most of the hal and graphics blob, which roll back most of the rom to 4.1.2

**Comment by adrian-bl** [comment]
I'm using the camera + hwcomposer blobs from 253 - that doesn't roll back 'most' of the rom to 4.1.2.
The nice thing is that the 253 base is pretty stable - no on-screen-delay or speaker bug present.

**Comment by Kali-** [comment]
guess u are referring to fixed cm bug (the wake delay depend on some patch which are on review, but is fixed)

anyway, this is not a chat, better to continue on a proper way, u can find me on #freexperia on freenode

**Comment by jredestig** [comment]
The reason why audio dont work is something entirely different.

**Comment by adrian-bl** [comment]
@jredestig: The patch + the audio blobs/firmware from the 253 release _does_ make audio work on AOSP.

**Comment by jredestig** [comment]
Oh, I did not realize you were talking about blobs here.

**Comment by anamaghrebi** [comment]
Hello,
I just started using aosp for xperia z, and I have used both patches mentionned above, but I still cannot get the sound to work. I'm using android-4.3_r3.1.

Has anyone tried?

Regards,

**Comment by sonyxperiadev** [comment]
modem has to be loaded for audio to work
